project:
  type: website
  output-dir: docs

website:
  title: "EC551 : Statistique Descriptive"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "TD1 : Statistiques univariées"
      - href: TD2.qmd
        text: "TD2 : Lien entre deux variables"
      - href: TD3.qmd
        text: "TD3 & TD4 : Préparation au projet"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  echo: true
  eval: false
  
lang: fr



