project:
  type: website
  output-dir: docs

website:
  title: "ECF932 : Techniques avancées en évaluation sensorielle"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Exercice 1 : Jus de fruits"
      - href: exo2.qmd
        text: "Exercice 2 : Parfums"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  echo: true
  eval: false
  
lang: fr




